k_list: [1, 3]
splits: ["test"]
metrics:
  - top1_accuracy
  - precision_at_k
  - recall_at_k
  - jaccard
  - acceptance_rate      # requires feedback.csv entries
  - time_to_evidence     # requires review_time_seconds
