rules:
  - control_id: "AU-8"
    any_keywords: ["ntp", "time drift", "time skew", "clock drift", "unsynced"]
    negative_keywords: ["tls", "cipher"]
    boost: 0.10
    dampen: 0.10

  - control_id: "SC-28"
    any_keywords: ["at rest", "s3 bucket", "disk encryption", "kms", "storage encryption"]
    boost: 0.08

  - control_id: "SC-12"
    any_keywords: ["kms", "key rotation", "key reuse", "key management"]
    boost: 0.06

  - control_id: "SC-8"
    any_keywords: ["http ", " tls", "https", "in transit", "cipher"]
    negative_keywords: ["at rest", "disk"]
    boost: 0.08
    dampen: 0.06

  - control_id: "AC-7"
    any_keywords: ["failed login", "failed logins", "logon attempts", "lockout"]
    boost: 0.10

  - control_id: "CM-8"
    any_keywords: ["inventory", "asset inventory", "shadow it", "untracked devices"]
    boost: 0.08

  - control_id: "RA-5"
    any_keywords: ["vuln scan", "vulnerability scan", "unauthenticated scan", "weekly scan"]
    boost: 0.08

  - control_id: "SA-11"
    any_keywords: ["sast", "dast", "code review", "ci pipeline", "secret scanning"]
    boost: 0.08
